generate:
  image: golang:1.15-alpine
  only:
    - master
  variables:
    deploy_path: "/www/wwwroot/kwokronny.top"
    app_name: "kb-comment"
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cd server
    - export GOPROXY=https://goproxy.io
    - cat go.mod
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "$app_name" main.go
    - scp -P"$SERVER_PORT" -r "$app_name" root@"$SERVER_HOST":"$deploy_path"
    - ssh -p"$SERVER_PORT" root@"$SERVER_HOST" "cd $deploy_path && nohup $app_name >> log.out & sleep 1"
