generate:
  image: golang:1.15-alpine
  only:
    - master
  variables:
    deploy_path: "/www/wwwroot/kwokronny.top/server"
    tar_name: "kb-comment.release.tar.gz"
    app_name: "kb-comment"
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cd server
    - export GOPROXY=https://goproxy.io
    - mkdir -p release/logs
    - cp -r templates release
    - cp -r config release
    - echo "$API_CONFIG" > ./release/config.yaml
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o release/"$app_name" main.go
    - cd release
    - tar -zcvf "$tar_name" ./*
    - scp -P"$SERVER_PORT" -r "$app_name" root@"$SERVER_HOST":"$deploy_path"
    - ssh -p"$SERVER_PORT" root@"$SERVER_HOST" "pkill -9 $app_name && tar -zxvf $tar_name -C $deploy_path && chmod 774 ${deploy_path}/${app_name} && nohup ${deploy_path}/${app_name} >> log.out & sleep 1"
