generate:
  image: golang:1.15-alpine
  only:
    - master
  variables:
    deploy_path: "/www/wwwroot/kwokronny.top/yoz-comment"
    tar_name: "yoz-comment.release.tar.gz"
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update
    - apk add openssh-client nodejs npm
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - npm install cnpm --registry=https://registry.npm.taobao.org/ -g
    - cnpm install parcel-bundler -g
    - cnpm install
    - npm run build
    - go generate
    - export GOPROXY=https://goproxy.io
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o comment-app main.go
    - tar -zcvf "$tar_name" comment-app
    - scp -P"$SERVER_PORT" -r "$tar_name" root@"$SERVER_HOST":/root
    - ssh -p"$SERVER_PORT" root@"$SERVER_HOST" "mkdir ${deploy_path}; tar -zxvf $tar_name -C $deploy_path && cd $deploy_path && sh ./sever.sh"