generate:
  image: golang:1.15-alpine
  only:
    - master
  variables:
    deploy_path: "/www/wwwroot/kwokronny.top/server"
    tar_name: "kb-comment.release.tar.gz"
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk update
    - apk add openssh-client nodejs npm
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - cd client
    - npm install cnpm --registry=https://registry.npm.taobao.org/
    - cnpm install parcel-bundler -g
    - cnpm install
    - npm build
    - cd ../
    - export GOPROXY=https://goproxy.io
    - mkdir -p deploy/logs
    - cp -r templates deploy
    - cp -r config deploy
    - rm -f deploy/config/config.yaml
    - echo "$API_CONFIG" > ./deploy/config/config.yaml
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o deploy/comment-app main.go
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o deploy/install install.go
    - cd deploy
    - tar -zcvf "$tar_name" ./*
    - scp -P"$SERVER_PORT" -r "$tar_name" root@"$SERVER_HOST":/root
    - ssh -p"$SERVER_PORT" root@"$SERVER_HOST" "pkill -9 $app_name ; mkdir ${deploy_path} ; tar -zxvf $tar_name -C $deploy_path && cd $deploy_path && sh ./server.sh"

public:
  image: golang:1.15-alpine
  only:
    - public
  script:
    - rm -rf .git
    - rm -f config/config.yaml
    - git init
    - git config --global user.email "green68599@icloud.com"
    - git config --global user.name "KwokRonny"
    - git config --global credential.helper store
    - git remote add origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/kwokronny/kb-comment.git"
    - git add .
    - git commit -m "同步仓库"
    - git push -u origin master