site_name: KwokRonny
site_url: https://kwokronny.top
server_port: 7550
mysql_host: kwok-nas.mokeyjay.com:3336
mysql_usr: root
mysql_pwd: gr68599$
mysql_db: comment
cros_enabled: true
manage_router: 8P4iZOql6VcSiFEVuDiPasnE80f3QIJ0MLgiTa
jwt_encrypt: bLNZbBbXPBKytrrYRsOXRDYSfS
admin_root: Hwq0za9WlCNSS7pT
admin_pass: 65931B6D2ADD30CCD16E7D23FAB32031
smtp_enabled: true
smtp_host: smtp.qq.com
smtp_port: 465
smtp_username: 204852001@qq.com
smtp_password: vhqknjsixlurcaie
smtp_to: 540476284@qq.com
log_file_path: ./logs/
sensitive_path: ./config/sensitive.txt