site_name: ""
site_url: ""
server_port: 9975
mysql_host: "123"
mysql_usr: "123"
mysql_pwd: "123"
mysql_db: "123"
cros_enabled: false
manage_router: gkqoSDBxv43fgL9CP3pV9u
jwt_encrypt: wgbSIZflOUSVhsBkREgBQcXKsr
admin_root: gkqoSDBxv43fgL9CP3pV9u
admin_pass: c8a1537bd5390a6d233a41d3b207ca74
smtp_enabled: false
smtp_host: ""
smtp_port: 465
smtp_username: ""
smtp_password: ""
smtp_to: ""
sensitive_enabled: false
sensitive_path: ./config/sensitive.txt
