name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - uses: actions/setup-node@v2
      with:
        node-version: '10.16.0'

    - name: Build Comment Frontend
      run: |
        npm install
        npm run build

    - name: Bindata Frontend in app
      run: | 
        mkdir statics
        npm run bindata-install
        npm run bindata
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
